### ISSUE TITLE
Continuous delivery with Travis CI

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/howto#1]
It would be nice to automatically compile and deploy GH pages using Travis CI. Some inspiration: http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/

**Comment by msimacek** [comment]
Done. Note that docs for all branches are rebuilt at once, so this has the side effect that error in one branch will fail subsequent builds in other branches. It's because the version index is shared among all branches.
