### ISSUE TITLE
Calendar versioning

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/howto#18]
Currently HOWTO versions correspond to versions of Fedora release that giver HOWTO corresponds to. I think it would be better to make it use [Calendar Versioning](https://calver.org/) instead.

**Comment by mizdebsk** [comment]
@mkoncek What is your opinion on that?

**Comment by mkoncek** [comment]
For consistency with our testing framework, I am favoring Fedora release versioning.
Since major changes in Fedora take place from release to relase, it will also be easier to know which versions of the documentation need to be updated.

**Comment by mizdebsk** [comment]
I agree and I withdraw my original proposal of calendar versioning.
