### ISSUE TITLE
Continuous build of Antora version

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/howto#20]
We need to have TravisCI (or another automation, like CentOS CI) build Antora version of the HOWTO and push generated code to some git repository (most likely on pagure.io), from where docs.fedoraproject.org will be able to pull it and integrate with the website.

**Comment by pbokoc** [comment]
Hi,

Fedora Docs don't really care where the content is, we can pull from any publicly available git repo, so in theory it's fine to host the Antora-ready sources here. The only requirement is that you have to push the transformed sources (the product or `make antora`), we can't really run make as part of our build process. (We could, but let's actually not do that or everyone's going to start asking us to do the same for them.) 

Separating the sources into a different repo (e.g. on Pagure) could make it less confusing, I suppose.

Using CI sounds great. Right now we don't have true CI in Fedora Docs (we will eventually), so after your CI outputs Antora sources and pushes them somewhere, they should appear on the docs site within an hour. When we have actual CI and not just a cron job, it's going to be way quicker, of course.

Also, please update your readme, and explain the reasons why there are multiple sets of sources, where are they used/published, and how the update process works. I can help you with documenting that if you want.

**Comment by mizdebsk** [comment]
> The only requirement is that you have to push the transformed sources (the product or `make antora`), we can't really run make as part of our build process. (We could, but let's actually not do that or everyone's going to start asking us to do the same for them.)

That's the plan. We will continously build Antora version of the HOWTO and push it to some git repository, from where Fedora Docs will be able to pull it and build it.

> Separating the sources into a different repo (e.g. on Pagure) could make it less confusing, I suppose.

I'm fine with using either pagure.io or github.com for generated Antora code. Using github.com would easier as TravisCI is already authorized to push there. I'm not sure how easily TravisCI can be configured for pushing to pagure.io - I can't give TravisCI access to my personal private SSH key as it gives access to way too many systems, including the whole Fedora infrastructure.

> Also, please update your readme, and explain the reasons why there are multiple sets of sources, where are they used/published, and how the update process works.

We will. Thanks for pointing that out.

**Comment by mizdebsk** [comment]
This is not relevant any longer - Antora version is now committed directly to git repo, we don't need to build it.
