### ISSUE TITLE
Broken markup on startpage

### ISSUE THREAD

**Issue by matthiasbeyer** [fedora-java/howto#25]
```
INCLUDE_ASCIIDOC(../version-links)
```

Is shown on https://fedora-java.github.io/howto/latest/

**Comment by mizdebsk** [comment]
Thanks for the report. I've fixed the underlying issue in commit fab6db735b3bcca480eaff54f759257f0087c347, but the build failed. We are in the process of migrating the build process to a different platform (#20), so this issue should be fully fixed once the migration is complete.

**Comment by mizdebsk** [comment]
The issue should be fixed now. We migrated to Fedora Docs from GitHub Pages.
