### ISSUE TITLE
Gradle on Fedora Packaging Guidelines

### ISSUE THREAD

**Issue by didiksupriadi41** [fedora-java/howto#29]
Quoting abstract from https://docs.fedoraproject.org/en-US/java-packaging-howto/
> Abstract
> This document aims to help developers create and maintain Java packages in Fedora. It does not supersede or replace Java Packaging Guidelines, but rather aims to document tools and techniques used for packaging Java software on Fedora.

Since gradle is not available on Fedora, I think it should be removed from Fedora Packaging Guidelines.

**Comment by mizdebsk** [comment]
I agree that the parts about Gradle can be removed. Pull requests are welcome.
