### ISSUE TITLE
Document %_ivyxmldir

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/howto#7]
%_ivyxmldir should be documented in directory layout, similarly to %_mavenpomdir.

**Comment by msimacek** [comment]
Should it go to the "used by regular packages section"? IOW can it be directly (meaningfully) used by a packager - e.g. if I install an ivy.xml there manually (without metadata) would XMvn pick it up?

**Comment by mizdebsk** [comment]
Sorry, I didn't notice the question earlier.

> can it be directly (meaningfully) used by a packager - e.g. if I install an ivy.xml there manually (without metadata) would XMvn pick it up?

No, In the past it would, but currently XMvn relies on metadata to resolve all system artifacts.
